services:
  tv_server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # Default static asset version (can override)
      - ASSET_VERSION=V1.0.0
    volumes:
      - ./:/app
      - tv_server_node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  tv_server_node_modules:
